title: Privacy Studies Journal Inaugural Conference
email: privacy@teol.ku.dk
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://privacystudies.org # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Centre for Privacy Studies
address_line: Karen Blixens Plads 16, 2300 Copenhagen S 
telephone_number: (+45) 35 32 37 87
company_email: privacy@teol.ku.dk
google_map: https://www.openstreetmap.org/search?query=karen%20blixens%20plads%2016#map=17/55.66186/12.58996

# Social Link
twitter_link: https://twitter.com/privacy_ku

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
